### interesting columns (smaller & larger dataset)
cols_veh = ['HOUSEID', 'VEHID', 'DRVRCNT', 'HYBRID', 'FUELTYPE', 'HBHUR', 'GSYRGAL']
cols_hh = ['HOUSEID', 'HOMEOWN', 'HHSIZE', 'HHVEHCNT', 'HHFAMINC', 'WALK', 'BIKE','TAXI', 'TRAIN','BUS', \
               'HHSTATE', 'YOUNGCHILD', 'WRKCOUNT', 'URBRUR', 'HTHTNRNT', 'HTPPOPDN','HTRESDN']
cols_per = ['HOUSEID', 'PERSONID', 'R_AGE', 'EDUC', 'R_SEX', 'R_RACE', 'PRMACT',  'GT1JBLWK', 'WKFTPT', 'OCCAT', \
    'CARSHARE', 'RIDESHARE', 'DELIVER', 'HEALTH' ]

small_hh = ['HOUSEID', 'HOMEOWN', 'HHSIZE', 'HHVEHCNT', 'YOUNGCHILD', 'WRKCOUNT', 'URBRUR']
small_per = ['HOUSEID', 'PERSONID', 'R_AGE', 'EDUC', 'R_SEX', 'R_RACE', 'PRMACT', 'PAYPROF', 'GT1JBLWK', 'WKFTPT', 'OCCAT', \
    'HEALTH' ]

### categorical columns
cat_cols = ['R_SEX','R_RACE','PRMACT', 'HOMEOWN','WALK', 'BIKE','TAXI','TRAIN','BUS','URBRUR', 'EDUC' , 'GT1JBLWK', 'WKFTPT', 'OCCAT', 'HEALTH', \
  'HYBRID', 'FUELTYPE', 'HBHUR']

### dict for encoding categorical columns
cleanup = {
    'R_SEX': {1 : 'female', 2: 'male'}, 
    'R_RACE': {1 : 'white', 2: 'african_american', 3: 'asian',4:'native_american', 5: 'native_hawaiian', 6: 'pacific'},
    'PRMACT': {1:'working',2:'temporarily_absent_from_occupation',3:'unemployed',4:'homemaker',5:'school',6:'retired'},
    'HOMEOWN': {1: 'owned_home', 2:'rent'},
    'WALK': {1:'daily_walks', 2: 'weekly_walks', 3: 'monthly_walks', 4: 'yearly_walks', 5: 'no_walks'},
    'BIKE': {1:'daily_bike', 2: 'weekly_bike', 3: 'monthly_bike', 4: 'yearly_bike', 5: 'no_bike'},
    'TAXI': {1:'daily_taxi', 2: 'weekly_taxi', 3: 'monthly_taxe', 4: 'yearly_taxi', 5: 'no_taxi'},
    'TRAIN': {1:'daily_train', 2: 'weekly_train', 3: 'monthly_train', 4: 'yearly_train', 5: 'no_train'},
    'BUS': {1:'daily_bus', 2: 'weekly_bus', 3: 'monthly_bus', 4: 'yearly_bus', 5: 'no_bus'},
    'URBRUR': {1: 'urban', 2: 'rural'}, 
    'EDUC': {1: 'less_high_school', 2:'high_school', 3:'college', 4:'bachelors', 5: 'graduate'},
    'GT1JBLWK': {1: 'one_job_less', 2:'more_one_job'},
    'WKFTPT': {1: 'part_time', 2: 'part_time'},
    'OCCAT' : {1:'sales_service_job', 2:'administrative_job', 3:'manual_job', 4:'graduate_job'},
    'HEALTH': {1:'excellent_health', 2:'very_good_health',3:'good_health', 4:'fair_health', 5:'poor_health'},
    'HYBRID': {1:'hybrid', 2:'no_hybrid'}, 
    'FUELTYPE': {1: 'gas_fuel', 2:'diesel_fuel', 3:'alternative_fuel'},
    'HBHUR': {'C':'second_city', 'R':'rural', 'T':'small_town', 'U':'urban'},
}

replace_columns = {
    'HHVEHCNT' : 'Amount of Vehicles', 
    'HHFAMINC' : 'Family Income',
    'YOUNGCHILD': 'Amount of young children',
    'WRKCOUNT' : 'Amount of Workers in Household',
    'HTHTNRNT' : 'Rented buildings in area',
    'HTPPOPDN': 'Population density in area',
    'HTRESDN': 'Housing density in area',
    'R_AGE': 'Age',
    'CARSHARE': 'Usage of carsharing',
    'RIDESHARE': 'Usage of ridesharing',
    'DELIVER': 'Usage of delivery service',
    'VEHID': 'Vehicle ID',
    'DRVRCNT': 'Drivers in household',
    'GSYRGAL': 'Annual fuel consumption',
    'R_SEX_female' : 'female',
    'R_SEX_male' : 'male',
    'R_RACE_african_american' : 'african_american',
    'R_RACE_asian' : 'asian',
    'R_RACE_native_american': 'native american',
    'R_RACE_native_hawaiian' : 'hawaiian', 
    'R_RACE_pacific': 'pacific (race)', 
    'R_RACE_white': 'white (race)', 
    'PRMACT_-1' : 'no occupation given',
    'PRMACT_homemaker' : 'homemaker (OCC)', 
    'PRMACT_retired': 'retired (OCC)', 
    'PRMACT_school': 'pupil (OCC)',
    'PRMACT_temporarily_absent_from_occupation':'temp. unemployed (OCC)', 
    'PRMACT_unemployed': 'unemployed (OCC)',
    'PRMACT_working': 'working (OCC)', 
    'HOMEOWN_owned_home': 'owned home', 
    'HOMEOWN_rent': 'rented home',
    'WALK_daily_walks': 'daily walking', 
    'WALK_monthly_walks': 'monthly walking', 
    'WALK_no_walks': 'no walking',
    'WALK_weekly_walks': 'weekly walking', 
    'WALK_yearly_walks': 'yearly walking', 
    'BIKE_daily_bike': 'daily biking',
    'BIKE_monthly_bike': 'monthly biking', 
    'BIKE_no_bike': 'no biking', 
    'BIKE_weekly_bike': 'weekly biking',
    'BIKE_yearly_bike': 'yearly biking', 
    'TAXI_daily_taxi': 'daily taxi use', 
    'TAXI_monthly_taxe': 'mothly taxi use',
    'TAXI_no_taxi': 'no taxi use', 
    'TAXI_weekly_taxi': 'weekly taxi use',
    'TAXI_yearly_taxi': 'yearly taxi use',
    'TRAIN_daily_train': 'daily train use', 
    'TRAIN_monthly_train': 'monthly train use', 
    'TRAIN_no_train': 'no train use',
    'TRAIN_weekly_train': 'weekly train use', 
    'TRAIN_yearly_train': 'yearly train use', 
    'BUS_daily_bus': 'daily bus use',
    'BUS_monthly_bus': 'monthly bus use', 
    'BUS_no_bus': 'no bus use', 
    'BUS_weekly_bus': 'weekly bus use', 
    'BUS_yearly_bus': 'yearly bus use',
    'URBRUR_rural': 'rural location', 
    'URBRUR_urban': 'urban location', 
    'EDUC_-1': 'no eduaction given', 
    'EDUC_bachelors': 'bachelor\'s degree',
    'EDUC_college': 'college degree', 
    'EDUC_graduate': 'graduate degree', 
    'EDUC_high_school': 'high school degree',
    'EDUC_less_high_school': 'less than high school degree', 
    'GT1JBLWK_-1': 'no info on amount of jobs', 
    'GT1JBLWK_one_job_less': 'one job or less',
    'GT1JBLWK_more_one_job': 'more than one job', 
    'WKFTPT_-1' : 'no info', 
    'WKFTPT_part_time': 'working part time', 
    'OCCAT_-1': 'no info',
    'OCCAT_administrative_job': 'administrative job', 
    'OCCAT_graduate_job': 'graduate job', 
    'OCCAT_manual_job': 'manual job',
    'OCCAT_sales_service_job': 'sales/service job', 
    'HEALTH_excellent_health': 'excellent health',
    'HEALTH_fair_health': 'fair health', 
    'HEALTH_good_health': 'good health', 
    'HEALTH_poor_health': 'poor health',
    'HEALTH_very_good_health': 'very good health', 
    'HYBRID_hybrid': 'hybrid car', 
    'HYBRID_no_hybrid': 'no hybrid car',
    'FUELTYPE_alternative_fuel': 'alternative fuel', 
    'FUELTYPE_diesel_fuel': 'diesel fuel',
    'FUELTYPE_gas_fuel': 'gas fuel', 
    'HBHUR_S': 'suburban', 
    'HBHUR_rural': 'rural', 
    'HBHUR_second_city': 'second city',
    'HBHUR_small_town': 'small town', 
    'HBHUR_urban': 'urban'
}